# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrJdEY3IbA0CPYSYY-udcqS-YlGv5ANv
"""

class Solution:
  # declare a class named Solution
  def isPalindrome(self, x: int) -> bool:
    # palindrome will be calculated in a function named isPalindrome. It'll take a integer number x and return if the number is true or false
    return false if x < 0 else str(x)[::-1] == str(x)
    # if the x is negetive it's not palindrome
    # else if the string of the number x is equal with the string of the reserse of x, the number x will be palindrome, otherwise x is not palindrome